FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
EXPOSE 8080
EXPOSE 8081
WORKDIR /src
COPY DSProject.AuthApi.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "DSProject.AuthApi.dll"]
